#!/bin/bash
# ╔══════════════════════════════════════════════════════════════╗
# ║  Claude LinkedIn Automation — Interactive Installer v3.1.0  ║
# ╚══════════════════════════════════════════════════════════════╝
#
# Usage:
#   git clone https://github.com/videomakingio-gif/claude-linkedin-automation.git
#   cd claude-linkedin-automation
#   chmod +x install.sh && ./install.sh
#
# Flags:
#   --uninstall    Remove all installed symlinks/copies
#   --global       Skip wizard, install globally for Claude Code
#   --project      Skip wizard, install in current project
#
# Dependencies:
#   Optional: gum (brew install gum) — beautiful TUI selection boxes
#   Falls back to plain prompts if gum is not installed

set -e

SKILL_NAME="linkedin"
REPO_DIR="$(cd "$(dirname "$0")" && pwd)"
INSTALLED=()
HAS_GUM=false
command -v gum &>/dev/null && HAS_GUM=true

# ── Colors (fallback mode) ──
BOLD='\033[1m'
DIM='\033[2m'
GREEN='\033[0;32m'
CYAN='\033[0;36m'
YELLOW='\033[0;33m'
RED='\033[0;31m'
RESET='\033[0m'

# ── Output helpers ──
print_header() {
    echo ""
    if $HAS_GUM; then
        gum style \
            --border double \
            --border-foreground 99 \
            --padding "0 2" \
            --margin "0 1" \
            "Claude LinkedIn Automation" \
            "Installer v3.1.0"
    else
        echo -e "${BOLD}╔══════════════════════════════════════════════════════════╗${RESET}"
        echo -e "${BOLD}║   Claude LinkedIn Automation — Installer               ║${RESET}"
        echo -e "${BOLD}║   v3.1.0                                               ║${RESET}"
        echo -e "${BOLD}╚══════════════════════════════════════════════════════════╝${RESET}"
    fi
    echo ""
}

print_success() {
    if $HAS_GUM; then
        gum style --foreground 82 "  ✓ $1"
    else
        echo -e "  ${GREEN}✓${RESET} $1"
    fi
}

print_info() {
    if $HAS_GUM; then
        gum style --foreground 39 "  → $1"
    else
        echo -e "  ${CYAN}→${RESET} $1"
    fi
}

print_warn() {
    if $HAS_GUM; then
        gum style --foreground 214 "  ! $1"
    else
        echo -e "  ${YELLOW}!${RESET} $1"
    fi
}

print_error() {
    if $HAS_GUM; then
        gum style --foreground 196 "  ✗ $1"
    else
        echo -e "  ${RED}✗${RESET} $1"
    fi
}

# ── Symlink helper ──
create_symlink() {
    local target_dir="$1"
    local label="$2"

    mkdir -p "$target_dir"
    local skill_path="$target_dir/$SKILL_NAME"

    if [ -L "$skill_path" ]; then
        local current="$(readlink "$skill_path")"
        if [ "$current" = "$REPO_DIR" ]; then
            print_warn "$label: already installed (up to date)"
            return 0
        else
            print_info "$label: updating symlink"
            rm "$skill_path"
        fi
    elif [ -d "$skill_path" ]; then
        print_error "$label: directory exists at $skill_path — remove manually"
        return 1
    fi

    ln -s "$REPO_DIR" "$skill_path"
    print_success "$label: $skill_path"
    INSTALLED+=("$skill_path")
}

# ── Cursor install ──
install_cursor() {
    local scope="$1"
    local rules_content

    rules_content="# Claude LinkedIn Automation (auto-generated by install.sh)
# Source: $REPO_DIR/SKILL.md
# To update: cd $REPO_DIR && git pull && ./install.sh
# To remove: delete this file

$(cat "$REPO_DIR/SKILL.md")"

    if [ "$scope" = "global" ]; then
        local cursor_dir="$HOME/.cursor/rules"
        mkdir -p "$cursor_dir"
        echo "$rules_content" > "$cursor_dir/linkedin-automation.mdc"
        print_success "Cursor (global): $cursor_dir/linkedin-automation.mdc"
        INSTALLED+=("$cursor_dir/linkedin-automation.mdc")
    else
        local cursor_dir=".cursor/rules"
        mkdir -p "$cursor_dir"
        echo "$rules_content" > "$cursor_dir/linkedin-automation.mdc"
        print_success "Cursor (project): $cursor_dir/linkedin-automation.mdc"
        INSTALLED+=("$cursor_dir/linkedin-automation.mdc")
    fi
}

# ── Windsurf install ──
install_windsurf() {
    local scope="$1"

    if [ "$scope" = "global" ]; then
        local ws_file="$HOME/.windsurf/rules/linkedin-automation.md"
        mkdir -p "$HOME/.windsurf/rules"
        cp "$REPO_DIR/SKILL.md" "$ws_file"
        print_success "Windsurf (global): $ws_file"
        INSTALLED+=("$ws_file")
    else
        local ws_file=".windsurfrules/linkedin-automation.md"
        mkdir -p ".windsurfrules"
        cp "$REPO_DIR/SKILL.md" "$ws_file"
        print_success "Windsurf (project): $ws_file"
        INSTALLED+=("$ws_file")
    fi
}

# ── Uninstall ──
do_uninstall() {
    print_header

    if $HAS_GUM; then
        gum style --bold "Uninstalling..."
    else
        echo -e "${BOLD}Uninstalling...${RESET}"
    fi
    echo ""

    local found=0

    # Claude Code global
    if [ -L "$HOME/.claude/skills/$SKILL_NAME" ]; then
        rm "$HOME/.claude/skills/$SKILL_NAME"
        print_success "Removed: ~/.claude/skills/$SKILL_NAME"
        found=1
    fi

    # Claude Code project
    if [ -L ".claude/skills/$SKILL_NAME" ]; then
        rm ".claude/skills/$SKILL_NAME"
        print_success "Removed: .claude/skills/$SKILL_NAME"
        found=1
    fi

    # Cursor
    for f in "$HOME/.cursor/rules/linkedin-automation.mdc" ".cursor/rules/linkedin-automation.mdc"; do
        if [ -f "$f" ]; then
            rm "$f"
            print_success "Removed: $f"
            found=1
        fi
    done

    # Windsurf
    for f in "$HOME/.windsurf/rules/linkedin-automation.md" ".windsurfrules/linkedin-automation.md"; do
        if [ -f "$f" ]; then
            rm "$f"
            print_success "Removed: $f"
            found=1
        fi
    done

    if [ $found -eq 0 ]; then
        print_warn "No installations found."
    fi

    echo ""
}

# ── Wizard (gum) ──
run_wizard_gum() {
    print_header

    # ── Step 1: Scope ──
    gum style --bold "Step 1/3 — Where do you want to install?"
    echo ""
    scope_choice=$(gum choose \
        "Global     — available in ALL your projects (~/.claude/skills/)" \
        "Project    — available only in the CURRENT project (./.claude/skills/)" \
        "Both       — global + project")
    echo ""

    # ── Step 2: IDE ──
    gum style --bold "Step 2/3 — Which IDEs do you use?"
    echo ""
    ide_choices=$(gum choose --no-limit \
        "Claude Code" \
        "Cursor" \
        "Windsurf")
    echo ""

    # Parse choices
    local scope=""
    case "$scope_choice" in
        Global*)  scope="global" ;;
        Project*) scope="project" ;;
        Both*)    scope="both" ;;
    esac

    local use_cursor=false
    local use_windsurf=false
    echo "$ide_choices" | grep -q "Cursor" && use_cursor=true
    echo "$ide_choices" | grep -q "Windsurf" && use_windsurf=true

    # ── Step 3: Confirm ──
    gum style --bold "Step 3/3 — Confirm installation"
    echo ""

    local scope_label=""
    case $scope in
        global)  scope_label="Global" ;;
        project) scope_label="Project ($(pwd))" ;;
        both)    scope_label="Global + Project" ;;
    esac

    local ide_label
    ide_label=$(echo "$ide_choices" | tr '\n' ', ' | sed 's/,$//' | sed 's/,/, /g')

    gum style "  Scope: $scope_label"
    gum style "  IDEs:  $ide_label"
    echo ""

    gum confirm "Proceed with installation?" || { print_warn "Installation cancelled."; exit 0; }

    echo ""
    gum style --bold "Installing..."
    echo ""

    # ── Execute: Claude Code ──
    case $scope in
        global)
            create_symlink "$HOME/.claude/skills" "Claude Code (global)"
            ;;
        project)
            create_symlink ".claude/skills" "Claude Code (project)"
            ;;
        both)
            create_symlink "$HOME/.claude/skills" "Claude Code (global)"
            create_symlink ".claude/skills" "Claude Code (project)"
            ;;
    esac

    # ── Execute: Cursor ──
    if $use_cursor; then
        case $scope in
            global)  install_cursor "global" ;;
            project) install_cursor "project" ;;
            both)    install_cursor "global"; install_cursor "project" ;;
        esac
    fi

    # ── Execute: Windsurf ──
    if $use_windsurf; then
        case $scope in
            global)  install_windsurf "global" ;;
            project) install_windsurf "project" ;;
            both)    install_windsurf "global"; install_windsurf "project" ;;
        esac
    fi

    # ── Summary ──
    echo ""
    gum style --border normal --border-foreground 82 --padding "0 2" \
        "Installation complete!" \
        "" \
        "Command:    /linkedin" \
        "Update:     cd $REPO_DIR && git pull" \
        "Uninstall:  ./install.sh --uninstall" \
        "" \
        "Claude Code: symlink (auto-updates with git pull)" \
        "Cursor/Windsurf: file copy (re-run installer after pull)"
    echo ""
}

# ── Wizard (fallback) ──
run_wizard_fallback() {
    print_header

    # ── Step 1: Scope ──
    echo -e "${BOLD}Step 1/3 — Where do you want to install?${RESET}"
    echo ""
    echo "  1) Global   — available in ALL your projects (~/.claude/skills/)"
    echo "  2) Project  — available only in the CURRENT project (./.claude/skills/)"
    echo "  3) Both"
    echo ""
    read -p "  Choose [1/2/3] (default: 1): " scope_choice
    scope_choice="${scope_choice:-1}"
    echo ""

    # ── Step 2: IDE ──
    echo -e "${BOLD}Step 2/3 — Which IDEs do you use?${RESET}"
    echo ""
    echo "  1) Claude Code only"
    echo "  2) Claude Code + Cursor"
    echo "  3) Claude Code + Windsurf"
    echo "  4) Claude Code + Cursor + Windsurf"
    echo ""
    read -p "  Choose [1-4] (default: 1): " ide_choice
    ide_choice="${ide_choice:-1}"
    echo ""

    # ── Step 3: Confirm ──
    echo -e "${BOLD}Step 3/3 — Confirm installation${RESET}"
    echo ""

    case $scope_choice in
        1) echo -e "  Scope: ${CYAN}Global${RESET}" ;;
        2) echo -e "  Scope: ${CYAN}Project${RESET} ($(pwd))" ;;
        3) echo -e "  Scope: ${CYAN}Global + Project${RESET}" ;;
    esac

    case $ide_choice in
        1) echo -e "  IDEs:  ${CYAN}Claude Code${RESET}" ;;
        2) echo -e "  IDEs:  ${CYAN}Claude Code, Cursor${RESET}" ;;
        3) echo -e "  IDEs:  ${CYAN}Claude Code, Windsurf${RESET}" ;;
        4) echo -e "  IDEs:  ${CYAN}Claude Code, Cursor, Windsurf${RESET}" ;;
    esac

    echo ""
    read -p "  Proceed? [Y/n]: " confirm
    confirm="${confirm:-Y}"
    if [[ ! "$confirm" =~ ^[Yy]$ ]]; then
        echo ""
        print_warn "Installation cancelled."
        exit 0
    fi

    echo ""
    echo -e "${BOLD}Installing...${RESET}"
    echo ""

    # ── Execute: Claude Code ──
    case $scope_choice in
        1) create_symlink "$HOME/.claude/skills" "Claude Code (global)" ;;
        2) create_symlink ".claude/skills" "Claude Code (project)" ;;
        3)
            create_symlink "$HOME/.claude/skills" "Claude Code (global)"
            create_symlink ".claude/skills" "Claude Code (project)"
            ;;
    esac

    # ── Execute: Cursor ──
    if [[ "$ide_choice" =~ ^[24]$ ]]; then
        case $scope_choice in
            1) install_cursor "global" ;;
            2) install_cursor "project" ;;
            3) install_cursor "global"; install_cursor "project" ;;
        esac
    fi

    # ── Execute: Windsurf ──
    if [[ "$ide_choice" =~ ^[34]$ ]]; then
        case $scope_choice in
            1) install_windsurf "global" ;;
            2) install_windsurf "project" ;;
            3) install_windsurf "global"; install_windsurf "project" ;;
        esac
    fi

    # ── Summary ──
    echo ""
    echo -e "${BOLD}════════════════════════════════════════════════════════════${RESET}"
    echo ""

    if [ ${#INSTALLED[@]} -gt 0 ]; then
        echo -e "  ${GREEN}${BOLD}Installation complete!${RESET}"
        echo ""
        echo -e "  ${BOLD}Command:${RESET}    /linkedin"
        echo -e "  ${BOLD}Update:${RESET}     cd $REPO_DIR && git pull"
        echo -e "  ${BOLD}Uninstall:${RESET}  $REPO_DIR/install.sh --uninstall"
        echo ""
        echo -e "  ${DIM}Claude Code uses a symlink — git pull updates the skill automatically.${RESET}"
        echo -e "  ${DIM}Cursor/Windsurf use file copies — re-run the installer after git pull.${RESET}"
    else
        print_warn "Nothing was installed (already up to date)."
    fi
    echo ""
}

# ── CLI flags ──
case "${1:-}" in
    --uninstall)
        do_uninstall
        ;;
    --global)
        print_header
        if $HAS_GUM; then
            gum style --bold "Installing globally for Claude Code..."
        else
            echo -e "${BOLD}Installing globally for Claude Code...${RESET}"
        fi
        echo ""
        create_symlink "$HOME/.claude/skills" "Claude Code (global)"
        echo ""
        ;;
    --project)
        print_header
        if $HAS_GUM; then
            gum style --bold "Installing for current project..."
        else
            echo -e "${BOLD}Installing for current project...${RESET}"
        fi
        echo ""
        create_symlink ".claude/skills" "Claude Code (project)"
        echo ""
        ;;
    "")
        if $HAS_GUM; then
            run_wizard_gum
        else
            run_wizard_fallback
        fi
        ;;
    *)
        echo "Usage: ./install.sh [--global | --project | --uninstall]"
        echo "  No flags = interactive wizard"
        echo ""
        echo "  Install gum for a better experience: brew install gum"
        exit 1
        ;;
esac
